name:                lucid
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- storablevector
- fft
- array
- carray
- storablevector-carray
- JuicyPixels
- ffmpeg-light
- hsndfile
- hsndfile-storablevector

library:
  source-dirs: src

executables:
  lucid-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lucid

tests:
  lucid-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lucid
    - tasty
    - tasty-hunit
